export const FETCH_PHOTOS_REQUEST = 'FETCH PHOTOS REQUEST';
export const FETCH_PHOTOS_SUCCESS = 'FETCH PHOTOS SUCCESS';
export const FETCH_PHOTOS_FAILED = 'FETCH PHOTOS FAILED';
export const ADD_TO_FAVOURITES = 'ADD TO FAVOURITES';